apiVersion: apps/v1
kind: Deployment
metadata:
  name: caCenter
  labels:
    app: caCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caCenter
  template:
    metadata:
      labels:
        app: caCenter
    spec:
      containers:
        - name: caCenter
          image: username/caCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5